"""
Registry Manager — CRUD operations on mcp_registry.json.

The registry tracks every MCP ever generated by this system:
its location, tools, status, deployment info, and creation timestamp.
"""
from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Optional

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from config.paths import registry_path as resolve_registry_path
from events.types import EventTypes
from orchestrator.events import publish_event

if TYPE_CHECKING:
    from orchestrator.state import MCPFactoryState

console = Console()

REGISTRY_PATH = resolve_registry_path()


class RegistryManager:
    """Read/write access to mcp_registry.json."""

    def __init__(self, path: Path = REGISTRY_PATH):
        self.path = path
        self.path.parent.mkdir(parents=True, exist_ok=True)
        if not self.path.exists():
            self._write({"version": "1.0", "mcps": []})

    # ── Read ──────────────────────────────────────────────────────────────

    def load(self) -> dict:
        return json.loads(self.path.read_text(encoding="utf-8"))

    def get_all(self) -> list[dict]:
        return self.load().get("mcps", [])

    def get_by_name(self, name: str) -> Optional[dict]:
        return next((m for m in self.get_all() if m["name"] == name), None)

    def get_by_id(self, entry_id: str) -> Optional[dict]:
        return next((m for m in self.get_all() if m["id"] == entry_id), None)

    # ── Write ─────────────────────────────────────────────────────────────

    def add(self, entry: dict) -> dict:
        """Add a new MCP entry. Returns the entry with its assigned ID."""
        data = self.load()
        entry["id"] = str(uuid.uuid4())
        entry["created_at"] = datetime.now(timezone.utc).isoformat()
        data["mcps"].append(entry)
        self._write(data)
        return entry

    def update_status(self, name: str, status: str, **extra) -> None:
        """Update the status of an existing MCP entry."""
        data = self.load()
        for mcp in data["mcps"]:
            if mcp["name"] == name:
                mcp["status"] = status
                mcp.update(extra)
                mcp["updated_at"] = datetime.now(timezone.utc).isoformat()
                break
        self._write(data)

    def remove(self, name: str) -> bool:
        """Remove an MCP entry by name. Returns True if found and removed."""
        data = self.load()
        original_count = len(data["mcps"])
        data["mcps"] = [m for m in data["mcps"] if m["name"] != name]
        if len(data["mcps"]) < original_count:
            self._write(data)
            return True
        return False

    # ── Internal ──────────────────────────────────────────────────────────

    def _write(self, data: dict) -> None:
        self.path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def registry_updater_node(state: "MCPFactoryState") -> "MCPFactoryState":
    """LangGraph node: saves the generated MCP to the registry and summarises."""
    generated = state["generated_mcp"]
    req = generated.design.requirement

    registry = RegistryManager()
    publish_event(
        state,
        EventTypes.REGISTRY_UPDATE_STARTED,
        "registry_updater",
        "Updating MCP registry projection",
        payload={"mcp_name": req.mcp_name},
    )

    # Build registry entry
    entry = {
        "name": req.mcp_name,
        "description": req.description,
        "server_path": generated.server_path,
        "transport": req.transport,
        "output_mode": req.output_mode.value,
        "tools": [t.name for t in req.tools],
        "resources": [r.uri_template for r in req.resources],
        "dependencies": req.dependencies,
        "status": generated.status,
        "deployment_pid": generated.deployment_pid,
        "deployment_url": generated.deployment_url,
        "validation_passed": generated.validation_passed,
        "port": req.port if req.transport == "http" else None,
    }

    # Upsert: remove old entry with same name if exists, then add new
    registry.remove(req.mcp_name)
    saved = registry.add(entry)
    publish_event(
        state,
        EventTypes.REGISTRY_UPDATED,
        "registry_updater",
        "MCP registry projection updated",
        payload={"mcp_name": req.mcp_name, "registry_id": saved["id"]},
    )

    console.print(f"\n[green]  ✓ Registered → {req.mcp_name} (id: {saved['id'][:8]}...)[/green]")

    # Final summary panel
    _print_summary(req, generated, saved)

    return {**state, "phase": "done", "error": None}


def _print_summary(req, generated, entry: dict) -> None:
    """Print a rich summary table of the created MCP."""
    table = Table(show_header=False, box=None, padding=(0, 1))
    table.add_column("Field", style="bold cyan", width=18)
    table.add_column("Value", style="white")

    table.add_row("Name", req.mcp_name)
    table.add_row("Description", req.description)
    table.add_row("Transport", req.transport)
    table.add_row("Output mode", req.output_mode.value)
    table.add_row("Tools", ", ".join(t.name for t in req.tools) or "—")
    table.add_row("Resources", ", ".join(r.uri_template for r in req.resources) or "—")
    table.add_row("Dependencies", ", ".join(req.dependencies) or "none")
    table.add_row("File", generated.server_path)

    if generated.deployment_pid:
        table.add_row("PID", str(generated.deployment_pid))
    if generated.deployment_url:
        table.add_row("URL", generated.deployment_url)

    table.add_row("Registry ID", entry["id"])

    console.print()
    console.print(
        Panel(
            table,
            title="[bold green]🎉 MCP Factory — Done![/bold green]",
            border_style="green",
            padding=(1, 2),
        )
    )
